### ISSUE TITLE
Add VB.NET support

### ISSUE THREAD

**Issue by vickyrocky** [SonarSource/sonarqube-roslyn-sdk#100]
Hi,

I have written vb analyzer and was trying to package into jar file using this sdk but getting following warning and also jar file is not created.Please refer the screenshot:
![image](https://user-images.githubusercontent.com/11328232/45401822-146bc680-b670-11e8-8339-8141b52ce943.png)

[EDIT] also asked at https://community.sonarsource.com/t/writing-vb-net-custom-rule/2492

**Comment by pascalberger** [comment]
This would be an important feature for us.  We have projects in C# and VB.NET and custom Roslyn analyzers for them (some analyzers in the assembly are for C# only, some for VB.NET only, others for both languages). We would like to use the SDK to create a plugin for our analyzer, so that we can use SonarQube as central place for issue management, documentation and also manage quality gates with SonarQube. This won't be possible as long as the SDK doesn't support VB.NET. 

While the external issues feature helps in reporting issues from the custom analyzers in VB.NET projects it won't allow to use Quality Profiles in SonarQube for ruleset management.
