### ISSUE TITLE
 Roslyn-based custom rules not recognized on Visual Studio IDE

### ISSUE THREAD

**Issue by ArunaBalasubramanian** [SonarSource/sonarqube-roslyn-sdk#101]
I created a sample custom C# analyzer named "**TestAnalyzer**" to capture the invalid regex pattern. I used Roslyn SDK to generate the .jar file, installed it on the SQ server and added this rule to the relevant Quality Profile.

The Scanner for MSBuild rightly captured this rule in the analysis process and reported error.

![image](https://user-images.githubusercontent.com/24669266/46012418-cc748700-c0e6-11e8-8fc1-405e6a41d7e1.png)

I updated the SonarLint in Connected Mode in order to propagate the custom rules from SQ server. The "xxx.ruleset" file when opened in notepad ++ is updated with Custom analyzer.

![image](https://user-images.githubusercontent.com/24669266/46012613-69372480-c0e7-11e8-94a5-69840565e1cf.png)

However, on VS, the Custom analyzer is not seen and the issue is not reported. Am I missing something?

![image](https://user-images.githubusercontent.com/24669266/46012659-8bc93d80-c0e7-11e8-8f90-030518a7737c.png)

![image](https://user-images.githubusercontent.com/24669266/46012872-275aae00-c0e8-11e8-9c9d-e1c3734ec1de.png)

Roslyn SDK version - 2.0
Visual Studio 2017 - 15.7.3

**Comment by duncanp-sonar** [comment]
@ArunaBalasubramanian the short answer is that the Scanner for MSBuild knows how to handle third-party analyzers packaged using the SonarQube Roslyn SDK, but SonarLint doesn't.
The custom analyzer info appears in the ruleset created by SonarLint because SonarLint is using the same logic as used by the Scanner for MSBuild to generated the ruleset. However, SonarLint doesn't know how to install the third-party analyzer on the developer's machine, so the rules are not run.

It wasn't originally a goal of the SDK to make it work with SonarLint - the goal was to make the Scanner for MSBuild upload issues for third-party analyzers. Also, Connected Mode no longer adds any NuGet analyzer packages to the MSBuild projects in the solution, not even the Sonar ones (we received feedback that most users didn't want the projects to be updated with analyzer references), so it would be inconsistent if SonarLint started adding third-part analyzer packages.

Have you looked at [MMF-1332](https://jira.sonarsource.com/browse/MMF-1332) referred to in the readme for this repo? The goal of that MMF is to automatically import issues from all Roslyn analyzers to SonarQube/Cloud without the need to use the SonarQube Roslyn SDK.
From a user point of view, you would add the third-party analyzers you want to run to your MSBuild projects as normal (there's no need to install the SonarC#/VB analyzer NuGets if you have SonarLint installed). The third-party issues will appear in the IDE because you've referenced their NuGet packages.
When you analyze the projects using the Scanner for MSBuild, it won't remove the third-party analyzers; it will run them and the SonarC#/VB analyzers and upload all of the issues. The third-party issues will be uploaded as [_generic issues_](https://docs.sonarqube.org/display/SONAR/Generic+Issue+Data).

The feature will be available in the next version of SonarQube (v7.4, currently scheduled for mid-October). It also requires updated versions of the Scanner for MSBuild and the SonarC# plugin, which will be released in the next week or so.

**Comment by duncanp-sonar** [comment]
@ArunaBalasubramanian it's a known issues with SonarLint. See https://github.com/SonarSource/sonarlint-visualstudio/issues/176, which also describes a manual workaround.
