### ISSUE TITLE
Output an error if the analyzer is using an unsupported version of Roslyn at analysis time

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonarqube-roslyn-sdk#119]
Currently, if a newer version of Roslyn is used, the issues are simply not read, without any hint for the user on why this happens.

It would be nice to not allow the creation of the plugin if an unsupported version of Roslyn is being used.

Related:  #104 , [community thread](https://community.sonarsource.com/t/new-roslyn-analyzer-rule-does-not-run-in-sq-6-7-1/9441/4)

**Comment by duncanp-sonar** [comment]
See #117.

Short version - this isn't a problem we can fix in this SDK.

Long version:

There are three possible versions of Roslyn that are relevant:
1) the version referenced by this repo (**S**),
2) the version referenced by the analyzer (**A**), and
3) the version referenced by the tool (i.e. MSBuild/dotnet/VS) the user is using when building the projects they are trying analyze with their new analyzer (**B**)

Versions (S) and (A) are relevant when creating a new plugin using this SDK.
If A > S then the SDK will fail to create the plugin. Otherwise, the plugin will be created.

Versions (A) and (B) are relevant when trying to use the analyzer to analyze code as part of a build.
If A > B, the build tool won't be able to create instances of the analyzer because the version of Roslyn is too new. In this case, the build tool (actually the C# compiler) will output a warning, something like `Analyzer1: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.`

That's what happened in the case described in the community forum. The fact that the user in that case had manually increased the version of **S** to 2.9 so they could create the plugin for their analyzer is a red herring.

There's nothing we can do about it in this SDK, as we don't know at the point the plugin is created what the version B is.

It's possible that we could do something in the Scanner for MSBuild to make the warning from the compiler more visible, but I'm not sure. It would require some investigation.
