### ISSUE TITLE
Runtime requirement

### ISSUE THREAD

**Issue by AnanthaSubramanian** [SonarSource/sonarqube-roslyn-sdk#135]
Team,

Could you please help me know for building plugin from Source Code what is the requirement for build server?
I am using VS2017 15.7.6 version for creating nuget package, which eventually will be used to create a plugin.
Do I need to have complete version of Visual Studio installed to generate nuget package?

Regards,
Anantha

**Comment by duncanp-sonar** [comment]
* is this a question about running the SonarQube Roslyn SDK, or a generic question about building projects that produce NuGet packages?
* the title of the issue is "Runtime requirement" - did you mean "Build-time requirement"?

Microsoft provide specific installers for build agents that install a subset of VS: search for `build tools for visual studio 2017` / `build tools for visual studio 2019`.

**Comment by AnanthaSubramanian** [comment]
Yes, I meant build time requirement.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
