### ISSUE TITLE
Error Failed to install package: 'Microsoft.CSharp' already has a dependency defined for 'System.Dynamic.Runtime'

### ISSUE THREAD

**Issue by PeteBoyRocket** [SonarSource/sonarqube-roslyn-sdk#68]
Running this command 
`.\RoslynSonarQubePluginGenerator.exe /a:AWSSDK.S3`
Results in this error:

```Roslyn Analyzer Plugin Generator for SonarQube 1.0.0.0
[DEBUG] Parsed NuGet reference. Id: AWSSDK.S3, version:
[DEBUG] Fetching NuGet config files...
[DEBUG] Enabled package sources:
[DEBUG]     https://www.nuget.org/api/v2/, machine-wide: False
[DEBUG]     C:\LocalNuGetFeed, machine-wide: False
Attempting to locate package with id 'AWSSDK.S3'
[DEBUG] Number of packages located: 114
[DEBUG] Package versions:
  3.0.0.0-preview
  3.0.0.1-preview
  3.0.0.2-preview
  3.0.0.3-preview
  3.1.0.0
  3.1.1.0
  3.1.1.1
  3.1.2.0
  3.1.2.1
  3.1.3.0
  3.2.0.0-beta
  3.1.3.1
  3.1.3.2
  3.1.3.3
  3.1.3.4
  3.1.3.5
  3.1.3.6
  3.1.3.7
  3.1.3.8
  3.1.3.9
  3.2.1.0-beta
  3.1.3.10
  3.2.2.0-beta
  3.1.3.11
  3.1.3.12
  3.1.3.13
  3.2.2.1-beta
  3.2.3.0-beta
  3.1.4.0
  3.1.5.0
  3.2.3.1-beta
  3.1.6.0
  3.1.6.1
  3.1.6.2
  3.2.4.0-beta
  3.2.4.1-beta
  3.1.7.0
  3.1.7.1
  3.1.7.2
  3.1.8.0
  3.2.5-beta
  3.1.8.1
  3.2.6-beta
  3.1.8.2
  3.1.8.3
  3.1.9.0
  3.2.7-beta
  3.2.8-rc
  3.1.10.0
  3.3.0
  3.3.0.1
  3.3.0.2
  3.3.0.3
  3.3.0.4
  3.3.1
  3.3.1.1
  3.3.1.2
  3.3.2
  3.3.3
  3.3.4
  3.3.4.1
  3.3.5
  3.3.5.1
  3.3.5.2
  3.3.5.3
  3.3.5.4
  3.3.5.5
  3.3.5.6
  3.3.5.7
  3.3.5.8
  3.3.5.9
  3.3.5.10
  3.3.5.11
  3.3.5.12
  3.3.5.13
  3.3.5.14
  3.3.5.15
  3.3.5.16
  3.3.5.17
  3.3.6
  3.3.6.1
  3.3.6.2
  3.3.6.3
  3.3.7
  3.3.7.1
  3.3.8
  3.3.8.1
  3.3.8.2
  3.3.9
  3.3.10
  3.3.10.1
  3.3.10.2
  3.3.10.3
  3.3.10.4
  3.3.11
  3.3.11.1
  3.3.11.2
  3.3.11.3
  3.3.11.4
  3.3.12
  3.3.12.1
  3.3.13
  3.3.14
  3.3.15
  3.3.16
  3.3.16.1
  3.3.16.2
  3.3.17
  3.3.17.1
  3.3.17.2
  3.3.17.3
  3.3.18
  3.3.18.1
  3.3.18.2 - latest version

[DEBUG] Using version marked as latest.
Version was not specified. Using version 3.3.18.2.
[NuGet] Attempting to resolve dependency 'AWSSDK.Core (= 3.3.22.1 && < 3.4.0)'.
[NuGet] Attempting to resolve dependency 'Microsoft.Net.Http (= 2.2.29)'.
[NuGet] Attempting to resolve dependency 'Microsoft.Bcl (= 1.1.10)'.
[NuGet] Attempting to resolve dependency 'Microsoft.Bcl.Build (= 1.0.14)'.
[NuGet] Attempting to resolve dependency 'PCLStorage (= 1.0.2)'.
[NuGet] Attempting to resolve dependency 'Microsoft.Bcl.Async (= 1.0.165)'.
[NuGet] Attempting to resolve dependency 'PCLCrypto (= 1.0.2.15130)'.
[NuGet] Attempting to resolve dependency 'Validation (= 2.0.6 && < 3.0)'.
[NuGet] Attempting to resolve dependency 'Mono.Security (= 3.2.3.0 && < 4.0)'.
[NuGet] Attempting to resolve dependency 'Microsoft.NETCore.UniversalWindowsPlatform (= 5.2.2)'.
[NuGet] Attempting to resolve dependency 'Microsoft.NETCore (= 5.0.2)'.
[NuGet] Attempting to resolve dependency 'Microsoft.CSharp (= 4.0.1)'.
Failed to install package: 'Microsoft.CSharp' already has a dependency defined for 'System.Dynamic.Runtime'.
Check that there are released versions of the package, or specify a pre-release version identifier.```

**Comment by duncanp-sonar** [comment]
@PeteBoyRocket using the just-release v2.0 of the Roslyn SDK gets further (i.e. doesn't fail with this error), possibly because it uses a newer version of Roslyn.

The problem looks like it's to do with how the Roslyn SDK fetches dependencies. It was designed to work with simple Roslyn NuGet analyzer packages that contain just analyzers, which normally have only a few dependencies. The Roslyn SDK pulls down the transitive set of dependency packages, then loads all of the assemblies and checks to see if they contain any analyzers.

The _AWSSDK.S3_ package is a "general" NuGet package that happens to have some analyzers in it. The transitive set of dependency packages is huge, most of which don't contain analyzers. I ran v2.0 of the Roslyn SDK against the _AWSSDK.S3_ package, but killed it after a few minutes as it was still pulling down dependencies.

It might work if you leave it to run, but I'm not confident. Another option would be to see if the analyzers are defined in their own package and run against that directly.
If that doesn't work, then the only other manual workaround I can think of is it to author a NuGet package yourself that contains just the analyzer assemblies (you wouldn't have to publish it - the README.md for this repo describes how to use a local file system folder as a NuGet repo).

**Comment by sohrab1-shaikh** [comment]
Hi,
I am trying to write the custom ruleset for .Net application and run the rules on sonarqube.  
I have implemented the cusomt rules using "org.sonar.plugins.java.api" for java based application. I am looking for similar kind of SonarQube API to write the rules in java files that will scan the .Net (.cs) files.

Can you please guide.

**Comment by duncanp-sonar** [comment]
@sohrab1-shaikh,
There isn't a recommended way to write rules in Java that analyze _.cs_ files. The recommended approach is to write a Roslyn analyzer in C# or VB.Net. See the [Microsoft documentation](https://docs.microsoft.com/en-us/visualstudio/extensibility/getting-started-with-roslyn-analyzers?view=vs-2017) for more information. The readme of this repo describes what to do once you have a Roslyn analyzer.

Also, please don't reuse an existing issue for an unrelated question. In general, [the SonarSource community forum](https://community.sonarsource.com/c/help) is a better place to ask general questions as it is monitored by more people.

**Comment by kesaven** [comment]
Has anyone figured out how to fix the issue?

**Comment by duncanp-sonar** [comment]
@kesaven I don't have any suggestions to add to those I made on 27th March.

**Comment by duncanp-sonar** [comment]
FYI v3 of the plugin can now successfully analyse the current version of `awssdks3` (v3.7.8.2)

![image](https://user-images.githubusercontent.com/10757559/156166985-8eb99230-2cfd-4652-a1be-0731ac11c28c.png)
