### ISSUE TITLE
Status of Roslyn rules

### ISSUE THREAD

**Issue by tijana88** [SonarSource/sonarqube-roslyn-sdk#72]
Hi,
We are moving on implementing Roslyn as replacement to FXCOP rules so I wanted to check on status of this plugin and if it supports SQ 6.7.4 ? 
BR
Tijana

**Comment by BrightLight** [comment]
(Disclaimer: I'm just a SonarQube user :-))
Not sure if I understand this question correctly. Do you want to write your own Roslyn analyzer or do you want to use existing analyzers as a replacement for FxCop?
If the former: this SDK is meant to convert a nuget package (which contains a Roslyn analyzer) into a SonarQube plugin. So if you're writing your own analyzers, you can package them and use this SDK to convert the nuget package into a SonarQube plugin. I've used it for multiple analyzers (at the company where I work we're currently using SQ 6.7.3 and it works). But they should really update the nuget libraries because this SDK doesn't work for multi-target nuget packages, for instance (but that's fixable if you fork this repo)
If the latter: you can take one or several existing Roslyn analyzers and convert them into SonarQube plugins. To my understanding there currently exist two projects that are trying to rewrite FxCop rules as Roslyn-based analyzers: 
* on the one hand, there's Microsoft: https://github.com/dotnet/roslyn-analyzers (I don't know the status of this project and how much of the old FxCop rules they have already ported)
* on the other hand there is SonarQube itself. The SonarSource team seems to be working on integrating many of the former FxCop rules into the C# analyzer which comes with SonarQube: https://github.com/SonarSource/sonar-csharp
They even have a page that shows the current status of this effort: http://dist.sonarsource.com/reports/coverage/fxcop_c%23.html

**Comment by duncanp-sonar** [comment]
Closing this issue as it's been answered by @BrightLight.

**Comment by SK1469** [comment]
Hi ,

We are also interested in the mapping between the fxcop rules and sonarqube rules , but the link 
http://dist.sonarsource.com/reports/coverage/fxcop_c%23.html
seems to be not active. Will it be possible to share the mapping ?

Thanks
