### ISSUE TITLE
"Fail to instantiate class [org.sonar.plugins.roslynsdk.RoslynSdkGeneratedPlugin]" error on starting SonarQube

### ISSUE THREAD

**Issue by vshteyn** [SonarSource/sonarqube-roslyn-sdk#73]
Attempting to run generated plugin on Sonar 6.7LTS results in jre exception. "java.lang.IllegalStateException: Fail to instantiate class [org.sonar.plugins.roslynsdk.RoslynSdkGeneratedPlugin] of plugin [stylecopanalyzers]". 
Which Sonar versions it supports?

**Comment by duncanp-sonar** [comment]
The plugin should support all versions for SonarQube from the point at which is was released. It definitely supports SonarQube 6.7 (I've previously tested against 6.7 when answering a question on StackOverflow).

If the analyzer you are trying to wrap publicly available, and if so which one is it?

**Comment by vshteyn** [comment]
Thanks for the reply. Yes, it's publicly available https://github.com/DotNetAnalyzers/StyleCopAnalyzers

**Comment by duncanp-sonar** [comment]
I've just used the SDK to create a plugin for StyleCop v1.0.2 and dropped it into the _extensions\plugins_ server. The server (v6.7) started fine, and if I browse the rules in the UI I can see 187 rules in the StyleCop repository.

Command line: `RoslynSonarQubePluginGenerator.exe /a:stylecop.analyzers`
...which just picked the [current version from NuGet](https://www.nuget.org/packages/StyleCop.Analyzers).

Have a look at [this question on StackOverflow](https://stackoverflow.com/questions/39925651/stylecop-anayzers-plugin-for-sonarqube-does-not-allow-to-start-the-platform/39998529
) which sounds very similar. There isn't a definite answer, but it sounds like there might have been due to third party zip software which affected the creation of the jar file.

Were there are errors or warnings logged when you ran the SDK exe?

**Comment by vshteyn** [comment]
Thanks, that actually worked and plug-in generated! Would you also happen to know if there is a way to substitute those 187 rules that the StyleCop 1.0.2 comes with our own ruleset?

**Comment by duncanp-sonar** [comment]
By substitute, do you mean change which rules are enabled by default in SonarQube when you add the plugin? No, I don't think so. The SDK translates the metadata from the Roslyn diagnostic descriptors to a _rules.xml_ that is embedded in the jar. However, there doesn't seem to be an field in the _rules.xml_ that is the equivalent of the diagnostic _IsEnabledByDefault_ field.

I think you'll have to use the SonarQube UI to configure the rules you want the quality profile.
